// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal_PrograIII.Data;

#nullable disable

namespace ProyectoFinal_PrograIII.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250429025653_CreateDatabaseSchema")]
    partial class CreateDatabaseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nit")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("IdProveedor");

                    b.ToTable("compras");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.DetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadProductos")
                        .HasColumnType("int");

                    b.Property<int>("IdCompras")
                        .HasColumnType("int");

                    b.Property<int>("IdProductos")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoId1")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCompras");

                    b.HasIndex("IdProductos");

                    b.HasIndex("ProductoId1");

                    b.ToTable("DetallesCompra", (string)null);
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadProductos")
                        .HasColumnType("int");

                    b.Property<int>("IdPedidos")
                        .HasColumnType("int");

                    b.Property<int>("IdProductos")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdPedidos");

                    b.HasIndex("IdProductos");

                    b.ToTable("detallePedido", (string)null);
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.MovimientoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdCompras")
                        .HasColumnType("int");

                    b.Property<int?>("IdPedidos")
                        .HasColumnType("int");

                    b.Property<int>("IdProductos")
                        .HasColumnType("int")
                        .HasColumnName("IdProductos");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdCompras");

                    b.HasIndex("IdPedidos");

                    b.HasIndex("IdProductos");

                    b.HasIndex("ProductoId");

                    b.ToTable("movimientos_inventario", (string)null);
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Existencias")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nit")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("proveedores");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Compra", b =>
                {
                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.DetalleCompra", b =>
                {
                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Compra", "Compra")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("IdCompras")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetallesCompra_Compras");

                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProductos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DetallesCompra_Productos");

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.DetallePedido", b =>
                {
                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Pedido", "Pedido")
                        .WithMany("DetallesPedidos")
                        .HasForeignKey("IdPedidos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Producto", "Producto")
                        .WithMany("DetallesPedidos")
                        .HasForeignKey("IdProductos")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.MovimientoInventario", b =>
                {
                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Compra", "Compra")
                        .WithMany()
                        .HasForeignKey("IdCompras")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("IdPedidos")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProductos")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MovimientoInventario_Producto");

                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Producto", null)
                        .WithMany("MovimientosInventario")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Compra");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Pedido", b =>
                {
                    b.HasOne("ProyectoFinal_PrograIII.Modelo.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Compra", b =>
                {
                    b.Navigation("DetallesCompra");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Pedido", b =>
                {
                    b.Navigation("DetallesPedidos");
                });

            modelBuilder.Entity("ProyectoFinal_PrograIII.Modelo.Producto", b =>
                {
                    b.Navigation("DetallesCompra");

                    b.Navigation("DetallesPedidos");

                    b.Navigation("MovimientosInventario");
                });
#pragma warning restore 612, 618
        }
    }
}
